version: "3"
services:
  service:
    build: .
    environment:
      DB_DRIVER: "postgres"
      DB_DSN: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
      DEBUG: "true"
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ".:/go/src/github.com/deanobarnett/mood-tracker"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  test:
    build: .
    command: make docker.test
    links:
      - db
    volumes:
      - ".:/go/src/github.com/deanobarnett/mood-tracker"
volumes:
  pgdata:
